### ISSUE TITLE
Indicate the maximum number of multiple items requestable with one query

### ISSUE THREAD

**Issue by nichtich** [gbv/daiaspec#14]
As discussed in #13 there should be a defined way to get the maximum number of multiple items requestable with one query (with default value 1). Possible implementations:

* additional request URL  (e.g. `/config`)
* additional request parameter
* additional parameter value (e.g. `format=about`)
* additional HTTP Header (e.g. `X-DAIA-X-Maximum-Ids`)
* default response if no `id` parameter is given
* additional field in every response
* ...

A request with more than the maximum number of ids must result in a HTTP 413 (Request Entity Too Large) response.

**Comment by dmj** [comment]
I don't think this is neccessary. Define a minium value that must be supported in the specs. Everything else is under the responsibility of the service provider and service consumer. In practice everybody would request such information once and store it in a client's configuration. No one is going to request this value over and over again.

**Comment by lahmann** [comment]
Specifying a minimum value is certainly a good idea, but I think there should be also a maximum. As DAIA services are usually directly connected with the ILS there might be need to limit the maximum ids per request due to performance concerns. If this maximum limit is not available a client receiving a HTTP 400 or 413 could only fallback to the minimum. This would work, but it would be more comfortable to be able to retrieve the configuration of the DAIA webservice and adjust its settings accordingly. This does not happen once but anytime an error occurs.
Apart from being able to implement some automatic routines for fixing client-side configuration issues, having configuration information and details about the API available at a specified webservice-path (the DAIA webservice entry point?) would be very helpful for developers as well as those configuration information would provide the basics for getting a client up and running with the DAIA service in question.
Keeping this information in an additional request URL seems to be the implementation having the smallest effect on the past specification versions and would keep the overhead small: the information is not needed for every request but is always accessible if needed.

**Comment by nichtich** [comment]
The minimum value is and will always be 1 because querying multiple ids in one request is optional.

**Comment by dmj** [comment]
> The minimum value is and will always be 1 because querying multiple ids in one request is optional.
Exactly. 
> Keeping this information in an additional request URL seems to be the implementation with the smallest effect on the past specification versions 
Except that every DAIA webservice must implement this.

Maybe we can take #15 into consideration: If the client requests information for more documents than the webservice can handle in one request, then the webservice MUST include the list of the IDs it did not  look up in the response.

This way it's up to the client to take appropriate action and the webservice can vary the number depending on external factors (i.e. overall system load, ip address of requester etc.).

**Comment by nichtich** [comment]
good idea. How about the other way round (returning all processed ids), and how about error response for too many  and/or too long identifiers?

**Comment by dmj** [comment]
Next iteration: A client MAY request availability information for multiple documents. If the server cannot provide information for all requested documents but could provide information in a subsequent response it MAY include a HTTP Link header (RFC 5988) with the relation "next" that points to a URI the client should use for subsequent requests.

Example: The client requests information for 10 documents but the server can only provide 5 information units per response.

  GET http://example.org/daia.php?id=a|b|c|d|e|f|g|h|i|j

The server returns a document with information about the documents a, b, f, h and j. The response contains a HTTP Link header as follows:

  Link: <http://example.org/daia.php?id=c|d|e|g|j>; rel="next"

A client SHOULD use this link to retrieve the remaining information.

**Comment by nichtich** [comment]
Good idea! Implementing this in a DAIA server should not be much of a burden even if only one id can be queried (just strip the first id and `|` and return the remaining ids in a Link header), so I'd make it a MUST in the next version of daia specification. Existing DAIA servers that do not support multiple id queries, return an error if multiple ids are passed, so this solution is backwards-compatible enough.

**Comment by nichtich** [comment]
Done at http://gbv.github.io/daia/
